{% set name = "xleaflet" %}
{% set version = "0.11.1" %}
{% set sha256 = "0c0bf39f128a76708ec6c93d1662781fc7ae5d203ac214dd1144657b990d88be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xleaflet/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - xeus >=0.23.3,<0.24
    - xtl >=0.6.5,<0.7
    - xproperty >=0.10.0,<0.11
    - xwidgets >=0.20.0,<0.21
    - xtensor >=0.20.8,<22
  run:
    - xtensor >=0.20.8,<22

test:
  commands:
    - test -d ${PREFIX}/include/xleaflet  # [unix]
    - test -f ${PREFIX}/include/xleaflet/xmap.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xleaflet/xleafletConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xleaflet/xleafletConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xleaflet\xmap.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xleafletConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xleafletConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xleaflet
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ backend for the jupyter leaflet widget'
  doc_url: http://xleaflet.readthedocs.io
  dev_url: https://github.com/jupyter-xeus/xleaflet

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
