{% set name = "xleaflet" %}
{% set version = "0.16.0" %}
{% set sha256 = "1fe9a8f090b0e5db50685b96b0ff4dab76314436bad1b29007346e881960f7e0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xleaflet/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - xeus >=2.0.0,<3.0
    - xtl >=0.7.0,<0.8
    - xproperty >=0.11.0,<0.12
    - xwidgets >=0.26.0,<0.27
    - xtensor >=0.23.0,<24
  run:
    - xtensor >=0.23.0,<0.24

test:
  commands:
    - test -d ${PREFIX}/include/xleaflet  # [unix]
    - test -f ${PREFIX}/include/xleaflet/xmap.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xleaflet/xleafletConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xleaflet/xleafletConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xleaflet\xmap.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xleafletConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xleafletConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xleaflet
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ backend for the jupyter leaflet widget
  doc_url: http://xleaflet.readthedocs.io
  dev_url: https://github.com/jupyter-xeus/xleaflet

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
