{% set name = "xleaflet" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xleaflet/archive/{{ version }}.tar.gz
  sha256: 1bc85797f12195c35d2c4d31c1fd78c8e4625151e7cea62ec085491c9f89754b

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
  host:
    - xeus >=5.0.0,<6.0
    - xproperty >=0.12.0,<0.13
    - xwidgets >=0.29.0,<0.30
    - xtensor >=0.24.3,<0.25
  run:
    - xtensor >=0.24.3,<0.25

test:
  commands:
    - test -d ${PREFIX}/include/xleaflet  # [unix]
    - test -f ${PREFIX}/include/xleaflet/xmap.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xleaflet/xleafletConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xleaflet/xleafletConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xleaflet\xmap.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xleafletConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xleafletConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xleaflet
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ backend for the jupyter leaflet widget
  doc_url: http://xleaflet.readthedocs.io
  dev_url: https://github.com/jupyter-xeus/xleaflet

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
