{% set name = "xleaflet" %}
{% set version = "0.7.0" %}
{% set sha256 = "860cdfb5a7e71e3c72300f64c880eceb2e93e0f3b90990e9cf09799e0bda11c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xleaflet/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - xeus >=0.18.1,<0.19
    - xtl >=0.5.2,<0.6
    - xproperty >=0.8.1,<0.9
    - xwidgets >=0.16.1,<0.17
    - xtensor >=0.19.1,<20
  run:
    - xtensor >=0.19.1,<20

test:
  commands:
    - test -d ${PREFIX}/include/xleaflet  # [unix]
    - test -f ${PREFIX}/include/xleaflet/xmap.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xleaflet/xleafletConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xleaflet/xleafletConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xleaflet\xmap.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xleafletConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xleafletConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xleaflet
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ backend for the jupyter leaflet widget'
  doc_url: http://xleaflet.readthedocs.io
  dev_url: https://github.com/QuantStack/xleaflet

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
